name: tidy-path
version: 0.1
description: Small utility for cleaning up redundant system paths (and more maybe?)
maintainer: Michael Kareithi

dependencies:
  - base
  - text
  - directory
  - optparse-applicative
  - containers
  
executables:
  tidypath:
    main: Main.hs
    source-dirs: src
